# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_Id', models.IntegerField()),
                ('user_name', models.CharField(max_length=25)),
                ('user_fname', models.CharField(blank=True, max_length=40, null=True)),
                ('user_lname', models.CharField(blank=True, max_length=40, null=True)),
                ('user_email', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('user_password', models.CharField(max_length=255)),
                ('joining_date', models.DateTimeField()),
                ('user_dob', models.DateField()),
                ('user_gender', models.CharField(max_length=1)),
                ('user_pic', models.CharField(blank=True, max_length=255, null=True)),
                ('user_about', models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                'verbose_name': 'Users',
                'db_table': 'tbl_users',
                'managed': False,
                'verbose_name_plural': 'Users',
            },
        ),
    ]
